### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by matthewcordaro** [legacybass/Jeopardy#5]
@legacybass, I would like to contribute to your project.  Unfortunately, there is no licence stated and therefore defaults to a strict copyright.  If the spirit is open source and open distribution, I would recommend making this MIT or GPL, although there are other options to consider.

Information can be found here: https://choosealicense.com/

How to easily do it in the GUI is here: https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by legacybass** [comment]
Done and done. Thanks for pointing this out, it's something I never thought to worry about for these kinds of projects. As an FYI, however, I've been in the process of resurrecting this project to use React and the create-react-app tool. My goal is to write the front-end in React, Angular, and Vue and present their differences at an upcoming code camp. I've only just started, but I'm happy to push up what I have if you would like to see what's there.
